version: "3"

services:
  nats:
    image: nats:2.5
    expose:
      - "${NATS_PORT}"
    ports:
      - "8222:8222"
      - "6222:6222"
  postgresql_user:
    image: postgres:13
    environment:
      POSTGRES_USER: ${USERS_DB_USER}
      POSTGRES_PASSWORD: ${USERS_DB_PASS}
      POSTGRES_DB: ${USERS_DB_NAME}
    expose:
      - "${USERS_DB_PORT}"
    ports:
      - "${USERS_DB_PORT}:${USERS_DB_PORT}"
    # Logs all SQL statements
    command: ["postgres", "-c", "log_statement=all", "-p", "${USERS_DB_PORT}"]
  postgresql_post:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTS_DB_USER}
      POSTGRES_PASSWORD: ${POSTS_DB_PASS}
      POSTGRES_DB: ${POSTS_DB_NAME}
    expose:
      - "${POSTS_DB_PORT}"
    ports:
      - "${POSTS_DB_PORT}:${POSTS_DB_PORT}"
    command: ["postgres", "-c", "log_statement=all", "-p", "${POSTS_DB_PORT}"]
  users:
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - postgresql_user
    environment:
      - USERS_DB_USER
      - USERS_DB_PASS
      - USERS_DB_NAME
      - USERS_DB_HOST
      - USERS_DB_PORT
      - USERS_PORT
    ports:
      - "${USERS_PORT}:${USERS_PORT}"
    # TODO Remove harcoded sleep in docker-compose
    # added because healthcheck doesn't work
    command: sh -c "sleep 10 && ./users"
  posts:
    build:
      context: ./post
      dockerfile: Dockerfile
    depends_on:
      - postgresql_post
      - nats
      - users
    environment:
      - POSTS_DB_USER
      - POSTS_DB_PASS
      - POSTS_DB_NAME
      - POSTS_DB_HOST
      - POSTS_DB_PORT
      - POSTS_NATS_HOST
      - POSTS_NATS_PORT
      - POSTS_USERS_GRPC_HOST
      - POSTS_USERS_GRPC_PORT
      - POSTS_NATS_SUBSCRIPTION_NAME
      - POSTS_NATS_DEADLETTER_NAME
      - POSTS_HTTP_PORT
    ports:
      - "${POSTS_HTTP_PORT}:${POSTS_HTTP_PORT}"
    command: sh -c "sleep 10 && ./posts"
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - nats
      - users
      - posts
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    environment:
      - NATS_SERVER_USER
      - NATS_SERVER_PASSWORD
      - NATS_SERVER_SUBJECT
      - NATS_SERVER_HOST
      - NATS_SERVER_PORT
      - USER_SERVICE_ADDRESS
      - TOKEN_TTL
      - TOKEN_SALT
      - POST_REST_API_URL
      - GATEWAY_PORT

