#! /bin/bash

set -e

# Silly curl's shortcuts to test stuff

if [ $1 = "create" ];
then
  if [ -z $2 ];
  then
    echo "pass an auth token"
    exit 1
  fi
  curl -v -X POST \
  -H 'Content-type: application/json' \
  -H "Authorization: Bearer ${2}" \
  -d '{"content":"```something in a block```","title":"markdown test","creator":"mountolive", "tags":["test"]}' \
  "http://localhost:8003/posts"
  exit $?
fi

if [ $1 = "update" ];
then
  if [ -z $2 ];
  then
    echo "pass the id of a post to be updated"
    exit 1
  fi
  if [ -z $3 ];
  then
    echo "pass an auth token"
    exit 1
  fi
  curl -v -X PUT \
  -H 'Content-type: application/json' \
  -H "Authorization: Bearer ${3}" \
  -d "{\"content\":\"something-better\",\"title\":\"best-title\",\"creator\":\"mountolive\", \"tags\":[\"awesome\"]}" \
  "http://localhost:8003/posts/${2}"
  exit $?
fi

if [ $1 = "read" ];
then
  if [ -z $2 ];
  then
    echo "pass the id of a post to be read"
    exit 1
  fi
  curl -v "http://localhost:8003/posts/${2}"
  exit $?
fi

if [ $1 = "login" ];
then
  if [ $# != 3 ];
  then
    echo "pass the test username and the test password"
    exit 1
  fi
  curl -X POST \
  -H 'Content-type: application/json' \
  -d "{\"username\":\"${2}\",\"password\":\"${3}\"}" \
  "http://localhost:8003/user"
  exit $?
fi

echo "action not supported"
exit 1
