#! /bin/bash

if [ $1 = "create" ];
then
	curl -X POST \
	-H 'Content-type: application/json' \
	-d "{\"content\":\"something\",\"title\":\"title\",\"creator\":\"mountolive\", \"tags\":[\"test\"]}" \
	"http://localhost:8003/posts"
  exit $?
fi

echo "action not supported"
