// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

package user

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = proto.Marshal
	_ = fmt.Errorf
	_ = math.Inf
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username             string               `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            string               `protobuf:"bytes,4,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string               `protobuf:"bytes,5,opt,name=lastName,proto3" json:"lastName,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{0}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}

func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}

func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}

func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}

func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *UserResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CheckUserRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUserRequest) Reset()         { *m = CheckUserRequest{} }
func (m *CheckUserRequest) String() string { return proto.CompactTextString(m) }
func (*CheckUserRequest) ProtoMessage()    {}
func (*CheckUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{1}
}

func (m *CheckUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUserRequest.Unmarshal(m, b)
}

func (m *CheckUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUserRequest.Marshal(b, m, deterministic)
}

func (m *CheckUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUserRequest.Merge(m, src)
}

func (m *CheckUserRequest) XXX_Size() int {
	return xxx_messageInfo_CheckUserRequest.Size(m)
}

func (m *CheckUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUserRequest proto.InternalMessageInfo

func (m *CheckUserRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func init() {
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
	proto.RegisterType((*CheckUserRequest)(nil), "user.CheckUserRequest")
}

func init() {
	proto.RegisterFile("user/user.proto", fileDescriptor_ed89022014131a74)
}

var fileDescriptor_ed89022014131a74 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xbf, 0x4f, 0x83, 0x40,
	0x14, 0x16, 0xa4, 0x58, 0x9e, 0x46, 0xcd, 0x8b, 0x31, 0x84, 0x98, 0xd8, 0x30, 0x31, 0x1d, 0x49,
	0x5d, 0x74, 0xac, 0xee, 0x0e, 0x44, 0x17, 0x37, 0x5a, 0x5e, 0xf1, 0x22, 0x70, 0x78, 0x77, 0xfc,
	0xfb, 0xc6, 0xdc, 0x1d, 0x50, 0xe3, 0xd2, 0x85, 0xf0, 0xfd, 0x7a, 0xe1, 0xfb, 0x80, 0xab, 0x41,
	0x91, 0xcc, 0xcd, 0x83, 0xf5, 0x52, 0x68, 0x81, 0x81, 0x79, 0x4f, 0xee, 0x6b, 0x21, 0xea, 0x86,
	0x72, 0xcb, 0x6d, 0x87, 0x7d, 0xae, 0x79, 0x4b, 0x4a, 0x97, 0x6d, 0xef, 0x6c, 0xe9, 0x8f, 0x07,
	0x17, 0xef, 0x8a, 0x64, 0x41, 0xaa, 0x17, 0x9d, 0x22, 0xbc, 0x04, 0x9f, 0x57, 0xb1, 0xb7, 0xf2,
	0xb2, 0xa8, 0xf0, 0x79, 0x85, 0x37, 0xb0, 0xa0, 0xb6, 0xe4, 0x4d, 0xec, 0x5b, 0xca, 0x01, 0x4c,
	0x60, 0x69, 0xee, 0x77, 0x65, 0x4b, 0xf1, 0xa9, 0x15, 0x66, 0x8c, 0x77, 0x10, 0xed, 0xb9, 0x54,
	0xfa, 0xd5, 0x88, 0x81, 0x15, 0x0f, 0x84, 0x49, 0x36, 0xe5, 0x28, 0x2e, 0x5c, 0x72, 0xc2, 0xf8,
	0x08, 0xd1, 0x4e, 0x52, 0xa9, 0xa9, 0xda, 0xe8, 0x38, 0x5c, 0x79, 0xd9, 0xf9, 0x3a, 0x61, 0xae,
	0x01, 0x9b, 0x1a, 0xb0, 0xb7, 0xa9, 0x41, 0x71, 0x30, 0x9b, 0xe4, 0xd0, 0x57, 0x63, 0xf2, 0xec,
	0x78, 0x72, 0x36, 0xa7, 0x19, 0x5c, 0xbf, 0x7c, 0xd2, 0xee, 0xcb, 0x8d, 0xf0, 0x3d, 0x90, 0xd2,
	0xa6, 0x73, 0x23, 0x6a, 0xde, 0x8d, 0x33, 0x38, 0xb0, 0xde, 0x40, 0x60, 0x4c, 0xf8, 0x04, 0xd1,
	0x9c, 0xc0, 0x5b, 0x66, 0x37, 0xff, 0x7f, 0x22, 0x41, 0xc7, 0xff, 0x9d, 0x36, 0x3d, 0x79, 0x5e,
	0x7e, 0x84, 0xcc, 0xfe, 0xa4, 0x6d, 0x68, 0xbf, 0xea, 0xe1, 0x37, 0x00, 0x00, 0xff, 0xff, 0x45,
	0x35, 0x1b, 0xda, 0xb8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ context.Context
	_ grpc.ClientConnInterface
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	CheckUser(ctx context.Context, in *CheckUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) CheckUser(ctx context.Context, in *CheckUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user.User/CheckUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	CheckUser(context.Context, *CheckUserRequest) (*UserResponse, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct{}

func (*UnimplementedUserServer) CheckUser(ctx context.Context, req *CheckUserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUser not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_CheckUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CheckUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/CheckUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CheckUser(ctx, req.(*CheckUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckUser",
			Handler:    _User_CheckUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user.proto",
}
