dev:
	@deno run -A https://deno.land/x/aleph@v0.3.0-beta.19/cli.ts dev

start:
	@deno run -A https://deno.land/x/aleph@v0.3.0-beta.19/cli.ts start

build:
	@deno run -A https://deno.land/x/aleph@v0.3.0-beta.19/cli.ts build

